// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contact.proto

package myproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Contact_PhoneType int32

const (
	Contact_UNSET Contact_PhoneType = 0
	Contact_CELL  Contact_PhoneType = 1
	Contact_HOME  Contact_PhoneType = 2
)

var Contact_PhoneType_name = map[int32]string{
	0: "UNSET",
	1: "CELL",
	2: "HOME",
}

var Contact_PhoneType_value = map[string]int32{
	"UNSET": 0,
	"CELL":  1,
	"HOME":  2,
}

func (x Contact_PhoneType) String() string {
	return proto.EnumName(Contact_PhoneType_name, int32(x))
}

func (Contact_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{0, 0}
}

type Contact struct {
	Phone                []*Contact_PhoneNumber  `protobuf:"bytes,1,rep,name=phone,proto3" json:"phone,omitempty"`
	Email                []*wrappers.StringValue `protobuf:"bytes,2,rep,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{0}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetPhone() []*Contact_PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *Contact) GetEmail() []*wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

type Contact_PhoneNumber struct {
	Type                 Contact_PhoneType     `protobuf:"varint,1,opt,name=type,proto3,enum=Demo.Contact_PhoneType" json:"type,omitempty"`
	Number               *wrappers.StringValue `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Contact_PhoneNumber) Reset()         { *m = Contact_PhoneNumber{} }
func (m *Contact_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Contact_PhoneNumber) ProtoMessage()    {}
func (*Contact_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{0, 0}
}

func (m *Contact_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact_PhoneNumber.Unmarshal(m, b)
}
func (m *Contact_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Contact_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact_PhoneNumber.Merge(m, src)
}
func (m *Contact_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Contact_PhoneNumber.Size(m)
}
func (m *Contact_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Contact_PhoneNumber proto.InternalMessageInfo

func (m *Contact_PhoneNumber) GetType() Contact_PhoneType {
	if m != nil {
		return m.Type
	}
	return Contact_UNSET
}

func (m *Contact_PhoneNumber) GetNumber() *wrappers.StringValue {
	if m != nil {
		return m.Number
	}
	return nil
}

func init() {
	proto.RegisterEnum("Demo.Contact_PhoneType", Contact_PhoneType_name, Contact_PhoneType_value)
	proto.RegisterType((*Contact)(nil), "Demo.Contact")
	proto.RegisterType((*Contact_PhoneNumber)(nil), "Demo.Contact.PhoneNumber")
}

func init() { proto.RegisterFile("contact.proto", fileDescriptor_a5036fff2565fb15) }

var fileDescriptor_a5036fff2565fb15 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0x2b,
	0x49, 0x4c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x71, 0x49, 0xcd, 0xcd, 0x97,
	0x92, 0x4b, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x25, 0x95, 0xa6, 0xe9, 0x97, 0x17,
	0x25, 0x16, 0x14, 0xa4, 0x16, 0x15, 0x43, 0x54, 0x29, 0xf5, 0x30, 0x71, 0xb1, 0x3b, 0x43, 0xf4,
	0x09, 0xe9, 0x73, 0xb1, 0x16, 0x64, 0xe4, 0xe7, 0xa5, 0x4a, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b,
	0x49, 0xea, 0x81, 0x4c, 0xd0, 0x83, 0xca, 0xea, 0x05, 0x80, 0xa4, 0xfc, 0x4a, 0x73, 0x93, 0x52,
	0x8b, 0x82, 0x20, 0xea, 0x84, 0x8c, 0xb8, 0x58, 0x53, 0x73, 0x13, 0x33, 0x73, 0x24, 0x98, 0xc0,
	0x1a, 0x64, 0xf4, 0x20, 0x96, 0xe9, 0xc1, 0x2c, 0xd3, 0x0b, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0x0f,
	0x4b, 0xcc, 0x29, 0x4d, 0x0d, 0x82, 0x28, 0x95, 0x2a, 0xe0, 0xe2, 0x46, 0x32, 0x49, 0x48, 0x9b,
	0x8b, 0xa5, 0xa4, 0xb2, 0x00, 0x64, 0x25, 0xa3, 0x06, 0x9f, 0x91, 0x38, 0x16, 0x2b, 0x43, 0x2a,
	0x0b, 0x52, 0x83, 0xc0, 0x8a, 0x84, 0x4c, 0xb8, 0xd8, 0xf2, 0xc0, 0xda, 0x24, 0x98, 0x14, 0x18,
	0x09, 0x5a, 0x08, 0x55, 0xab, 0xa4, 0xc5, 0xc5, 0x09, 0x37, 0x48, 0x88, 0x93, 0x8b, 0x35, 0xd4,
	0x2f, 0xd8, 0x35, 0x44, 0x80, 0x41, 0x88, 0x83, 0x8b, 0xc5, 0xd9, 0xd5, 0xc7, 0x47, 0x80, 0x11,
	0xc4, 0xf2, 0xf0, 0xf7, 0x75, 0x15, 0x60, 0x72, 0xe2, 0x8c, 0x62, 0xcf, 0xad, 0x84, 0x98, 0xc6,
	0x06, 0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x66, 0x93, 0xc2, 0x57, 0x01, 0x00,
	0x00,
}
