// Code generated by protoc-gen-go. DO NOT EDIT.
// source: location.proto

package myproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Location struct {
	Address1             *wrappers.StringValue `protobuf:"bytes,1,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2             *wrappers.StringValue `protobuf:"bytes,2,opt,name=address2,proto3" json:"address2,omitempty"`
	City                 *wrappers.StringValue `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State                *wrappers.StringValue `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  *wrappers.UInt32Value `protobuf:"bytes,5,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{0}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetAddress1() *wrappers.StringValue {
	if m != nil {
		return m.Address1
	}
	return nil
}

func (m *Location) GetAddress2() *wrappers.StringValue {
	if m != nil {
		return m.Address2
	}
	return nil
}

func (m *Location) GetCity() *wrappers.StringValue {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *Location) GetState() *wrappers.StringValue {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Location) GetZip() *wrappers.UInt32Value {
	if m != nil {
		return m.Zip
	}
	return nil
}

func init() {
	proto.RegisterType((*Location)(nil), "Demo.Location")
}

func init() { proto.RegisterFile("location.proto", fileDescriptor_4f0f35158dcf9f2c) }

var fileDescriptor_4f0f35158dcf9f2c = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xc9, 0x4f, 0x4e,
	0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x71, 0x49, 0xcd, 0xcd,
	0x97, 0x92, 0x4b, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x25, 0x95, 0xa6, 0xe9, 0x97,
	0x17, 0x25, 0x16, 0x14, 0xa4, 0x16, 0x15, 0x43, 0x54, 0x29, 0x4d, 0x61, 0xe2, 0xe2, 0xf0, 0x81,
	0x6a, 0x14, 0xb2, 0xe0, 0xe2, 0x48, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x36, 0x94, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd1, 0x83, 0xe8, 0xd7, 0x83, 0xe9, 0xd7, 0x0b, 0x2e, 0x29, 0xca,
	0xcc, 0x4b, 0x0f, 0x4b, 0xcc, 0x29, 0x4d, 0x0d, 0x82, 0xab, 0x46, 0xd2, 0x69, 0x24, 0xc1, 0x44,
	0x82, 0x4e, 0x23, 0x21, 0x03, 0x2e, 0x96, 0xe4, 0xcc, 0x92, 0x4a, 0x09, 0x66, 0x22, 0x74, 0x81,
	0x55, 0x0a, 0x19, 0x71, 0xb1, 0x16, 0x97, 0x24, 0x96, 0xa4, 0x4a, 0xb0, 0x10, 0xa1, 0x05, 0xa2,
	0x54, 0x48, 0x8f, 0x8b, 0xb9, 0x2a, 0xb3, 0x40, 0x82, 0x15, 0x87, 0x8e, 0x50, 0xcf, 0xbc, 0x12,
	0x63, 0x23, 0x88, 0x0e, 0x90, 0x42, 0x27, 0xce, 0x28, 0xf6, 0xdc, 0x4a, 0x88, 0x34, 0x1b, 0x98,
	0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x61, 0x19, 0xac, 0x60, 0x01, 0x00, 0x00,
}
