// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package myproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_Prefix int32

const (
	Person_PFX_UNSET Person_Prefix = 0
	Person_MR        Person_Prefix = 1
	Person_MS        Person_Prefix = 2
	Person_MRS       Person_Prefix = 3
)

var Person_Prefix_name = map[int32]string{
	0: "PFX_UNSET",
	1: "MR",
	2: "MS",
	3: "MRS",
}

var Person_Prefix_value = map[string]int32{
	"PFX_UNSET": 0,
	"MR":        1,
	"MS":        2,
	"MRS":       3,
}

func (x Person_Prefix) String() string {
	return proto.EnumName(Person_Prefix_name, int32(x))
}

func (Person_Prefix) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0, 0}
}

type Person_Suffix int32

const (
	Person_SFX_UNSET Person_Suffix = 0
	Person_JR        Person_Suffix = 1
	Person_SR        Person_Suffix = 2
)

var Person_Suffix_name = map[int32]string{
	0: "SFX_UNSET",
	1: "JR",
	2: "SR",
}

var Person_Suffix_value = map[string]int32{
	"SFX_UNSET": 0,
	"JR":        1,
	"SR":        2,
}

func (x Person_Suffix) String() string {
	return proto.EnumName(Person_Suffix_name, int32(x))
}

func (Person_Suffix) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0, 1}
}

type Person struct {
	Prefix               Person_Prefix         `protobuf:"varint,1,opt,name=prefix,proto3,enum=Demo.Person_Prefix" json:"prefix,omitempty"`
	First                *wrappers.StringValue `protobuf:"bytes,2,opt,name=first,proto3" json:"first,omitempty"`
	Last                 *wrappers.StringValue `protobuf:"bytes,3,opt,name=last,proto3" json:"last,omitempty"`
	Suffix               Person_Suffix         `protobuf:"varint,4,opt,name=suffix,proto3,enum=Demo.Person_Suffix" json:"suffix,omitempty"`
	Location             *Location             `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Contact              *Contact              `protobuf:"bytes,6,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetPrefix() Person_Prefix {
	if m != nil {
		return m.Prefix
	}
	return Person_PFX_UNSET
}

func (m *Person) GetFirst() *wrappers.StringValue {
	if m != nil {
		return m.First
	}
	return nil
}

func (m *Person) GetLast() *wrappers.StringValue {
	if m != nil {
		return m.Last
	}
	return nil
}

func (m *Person) GetSuffix() Person_Suffix {
	if m != nil {
		return m.Suffix
	}
	return Person_SFX_UNSET
}

func (m *Person) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Person) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func init() {
	proto.RegisterEnum("Demo.Person_Prefix", Person_Prefix_name, Person_Prefix_value)
	proto.RegisterEnum("Demo.Person_Suffix", Person_Suffix_name, Person_Suffix_value)
	proto.RegisterType((*Person)(nil), "Demo.Person")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x69, 0xba, 0xb1, 0xa3, 0x09, 0x61, 0xbd, 0x84, 0x22, 0x52, 0x72, 0x69, 0x51, 0xd8,
	0x96, 0xf8, 0x0f, 0xfc, 0x3a, 0x88, 0x95, 0xb0, 0xab, 0x22, 0x5e, 0x24, 0x86, 0x24, 0x04, 0xd2,
	0x6c, 0xd8, 0x6c, 0x50, 0xff, 0xb9, 0x47, 0xc9, 0xee, 0x46, 0x10, 0x3c, 0x78, 0x1a, 0x66, 0xde,
	0x7b, 0xf3, 0xde, 0x0c, 0x1c, 0xb6, 0xb9, 0xe8, 0x78, 0x43, 0x5a, 0xc1, 0x25, 0xc7, 0xce, 0x55,
	0xbe, 0xe3, 0x73, 0xbf, 0xe6, 0x59, 0x2a, 0xab, 0x71, 0x3a, 0xf7, 0x32, 0xde, 0xc8, 0x34, 0x93,
	0xa6, 0x3d, 0x29, 0x39, 0x2f, 0xeb, 0x7c, 0xad, 0xba, 0xb7, 0xbe, 0x58, 0xbf, 0x8b, 0xb4, 0x1d,
	0xd6, 0x68, 0x3c, 0xfa, 0xb2, 0x01, 0x25, 0x6a, 0x2b, 0x3e, 0x03, 0xd4, 0x8a, 0xbc, 0xa8, 0x3e,
	0x42, 0x6b, 0x61, 0xad, 0xfc, 0xf8, 0x88, 0x0c, 0x06, 0x44, 0xa3, 0x24, 0x51, 0x10, 0x35, 0x14,
	0x1c, 0xc3, 0xb4, 0xa8, 0x44, 0x27, 0x43, 0x7b, 0x61, 0xad, 0x0e, 0xe2, 0x63, 0xa2, 0x7d, 0xc8,
	0xe8, 0x43, 0x98, 0x14, 0x55, 0x53, 0x3e, 0xa5, 0x75, 0x9f, 0x53, 0x4d, 0xc5, 0x1b, 0x70, 0xea,
	0xb4, 0x93, 0xe1, 0xe4, 0x1f, 0x12, 0xc5, 0x1c, 0x22, 0x75, 0x7d, 0x31, 0x44, 0x72, 0xfe, 0x88,
	0xc4, 0x14, 0x44, 0x0d, 0x05, 0x9f, 0xc2, 0xfe, 0xf8, 0x8b, 0x70, 0xaa, 0x2c, 0x7c, 0x4d, 0xbf,
	0x33, 0x53, 0xfa, 0x83, 0xe3, 0x25, 0xb8, 0xe6, 0x4f, 0x21, 0x52, 0x54, 0x4f, 0x53, 0x2f, 0xf5,
	0x90, 0x8e, 0x68, 0xb4, 0x01, 0xa4, 0x2f, 0xc7, 0x1e, 0xcc, 0x92, 0x9b, 0xe7, 0xd7, 0xc7, 0x7b,
	0x76, 0xfd, 0x10, 0xec, 0x61, 0x04, 0xf6, 0x96, 0x06, 0x96, 0xaa, 0x2c, 0xb0, 0xb1, 0x0b, 0x93,
	0x2d, 0x65, 0xc1, 0x24, 0x5a, 0x02, 0xd2, 0xc1, 0x06, 0x05, 0xfb, 0xad, 0xb8, 0x35, 0x0a, 0x46,
	0x03, 0xfb, 0x62, 0xf6, 0xe2, 0xee, 0x3e, 0xf5, 0xf1, 0x48, 0x95, 0xf3, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x48, 0x3f, 0x2b, 0xfa, 0xe1, 0x01, 0x00, 0x00,
}
